services:
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"


  backend:
    container_name: backend
    build: .
    env_file: ./envs/.env.backend
    ports:
      - "8000:8000"
    depends_on:
      - redis

  bot:
    build: .
    env_file: ./envs/.env.bot
    working_dir: /app
    environment:
     - PYTHONPATH=/app/app
    command: python -m controllers.bot.main