"""post udTA

Revision ID: a8a36def710a
Revises: 7a21c73619bc
Create Date: 2025-10-07 21:00:58.292326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a36def710a'
down_revision: Union[str, Sequence[str], None] = '7a21c73619bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_messages')
    op.drop_table('direct_messages')
    op.drop_table('general_chats')
    op.drop_table('user_reaction_post')
    op.drop_table('direct_chats')
    op.drop_table('used_tokens')
    op.drop_table('general_chat_members')
    op.add_column('user_settings', sa.Column('private', sa.Boolean(), nullable=False))
    op.add_column('user_settings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user_settings', ['user_id'])
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.drop_constraint(None, 'user_settings', type_='unique')
    op.drop_column('user_settings', 'user_id')
    op.drop_column('user_settings', 'private')
    op.create_table('general_chat_members',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['general_chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.create_table('used_tokens',
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_chats',
    sa.Column('first_user_id', sa.INTEGER(), nullable=False),
    sa.Column('second_user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['first_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['second_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('first_user_id', 'second_user_id')
    )
    op.create_table('user_reaction_post',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('reaction', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('general_chats',
    sa.Column('private', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_messages',
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_messages',
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['general_chats.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
