"""empty message

Revision ID: c3ae0b3e874a
Revises: a8a36def710a
Create Date: 2025-10-08 21:54:16.620690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ae0b3e874a'
down_revision: Union[str, Sequence[str], None] = 'a8a36def710a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_reaction_post')
    op.drop_table('direct_messages')
    op.drop_table('used_tokens')
    op.drop_index(op.f('ix_direct_chat_users'), table_name='direct_chats')
    op.drop_table('direct_chats')
    op.drop_table('direct_user_settings')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_settings', sa.Column('is_profile_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'is_profile_public')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.create_table('direct_user_settings',
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('enable_notifications', sa.BOOLEAN(), nullable=False),
    sa.Column('chat_name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['direct_chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_table('direct_chats',
    sa.Column('first_user_id', sa.INTEGER(), nullable=False),
    sa.Column('second_user_id', sa.INTEGER(), nullable=False),
    sa.Column('banned_user_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['banned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['first_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['second_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_user_id', 'second_user_id', name=op.f('uq_direct_chat_users'))
    )
    op.create_index(op.f('ix_direct_chat_users'), 'direct_chats', ['first_user_id', 'second_user_id'], unique=False)
    op.create_table('used_tokens',
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_messages',
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_reaction_post',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('reaction', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###
